project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  name: "giantswarm/capg-firewall-rule-operator"
  tag: "[[ .Version ]]"
registry:
  domain: docker.io

managementClusterName: ""
managementClusterNamespace: ""
defaultAPIAllowList: "185.102.95.187/32,95.179.153.65/32"
defaultBastionHostAllowList: "185.102.95.187/32,95.179.153.65/32"

pod:
  user:
    id: 1000
  group:
    id: 1000

gcpProject: ""
