gcp:
  credentials: credentials
project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  name: "giantswarm/capg-firewall-rule-operator"
  tag: "[[ .Version ]]"
registry:
  domain: docker.io

pod:
  user:
    id: 1000
  group:
    id: 1000
