version: 2.1
orbs:
  architect: giantswarm/architect@4.17.0

jobs:
  unit-tests:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: CGO_ENABLED=0 make test-unit
  integration-tests:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run integration tests"
          command: CGO_ENABLED=0 make test-integration
  acceptance-tests:
    executor: architect/machine
    machine:
      image: 'ubuntu-2004:202010-01'
    steps:
      - checkout
      - architect/machine-install-go
      - architect/integration-test-install-tools:
          apptestctl-version: v0.14.1
          helm-version: v3.8.2
          kubernetes-version: v1.21.1
      - run:
          name: "Run acceptance tests"
          command: CGO_ENABLED=0 make test-acceptance
      - run:
          name: "Wait for deletion"
          when: always
          command: |
            echo "Waiting for cluster deletion"
            while [[ -n "$(kubectl get clusters --all-namespaces -o name)" ]]; do
              echo "-------------------------------"
              kubectl get clusters --all-namespaces
              sleep 1
            done

workflows:
  test-and-push:
    jobs:
      - unit-tests:
          filters:
            tags:
              only: /^v.*/
      - architect/go-build:
          context: architect
          name: go-build
          binary: capg-firewall-rule-operator
          resource_class: xlarge
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          context: architect
          name: push-capg-firewall-rule-operator-to-quay
          image: "quay.io/giantswarm/capg-firewall-rule-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
          - go-build
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          context: "architect"
          name: push-capg-firewall-rule-operator-to-docker
          image: "docker.io/giantswarm/capg-firewall-rule-operator"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
                k
    # Ensure that for every commit
    # there is an app version in the test catalog.
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "capg-firewall-rule-operator"
          requires:
          - push-capg-firewall-rule-operator-to-quay
          - push-capg-firewall-rule-operator-to-docker
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          context: architect
          name: push-to-gcp-app-collection
          app_name: "capg-firewall-rule-operator"
          app_collection_repo: "gcp-app-collection"
          requires:
          - push-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
