apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
  {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
  {{- include "labels.selector" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
    {{- if not .Values.gcp.credentials }}
        giantswarm.io/gcp-workload-identity: enabled
    {{- end }}
    {{- include "labels.selector" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "resource.default.name"  . }}
      securityContext:
        runAsUser: {{ .Values.pod.user.id }}
        runAsGroup: {{ .Values.pod.group.id }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.registry.domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command:
            - /manager
          {{- if .Values.gcp.credentials }}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /home/.gcp/credentials
          {{- end }}
          args:
            - "--management-cluster-name"
            - {{ .Values.managementClusterName }}
            - "--management-cluster-namespace"
            - {{ .Values.managementClusterNamespace }}
            - "--default-api-allow-list"
            - {{ .Values.defaultAPIAllowList }}
            - "--default-bastion-host-allow-list"
            - {{ .Values.defaultBastionHostAllowList }}
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 80Mi
          volumeMounts:
            - mountPath: /home/.gcp
              name: credentials
      terminationGracePeriodSeconds: 10
      {{- if .Values.gcp.credentials }}
      volumes:
        - name: credentials
          secret:
            secretName: {{ include "resource.default.name" . }}-gcp-credentials
      {{- end }}
